workflows:
  testing-workflow:
    name: iOS Workflow
    instance_type: mac_pro
    environment:
      vars:
        XCODE_PROJECT: "CountriesSwiftUI.xcodeproj"
        XCODE_SCHEME: "CountriesSwiftUI"
      xcode: latest
      cocoapods: default
    triggering:
      branch_patterns:
        - pattern: "master"
          include: true
          source: true
    scripts:
      - name: Run tests
        script: |
          xcode-project run-tests \
              --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --device "iPhone 12"
        test_report: build/ios/test/*.xml
